Nombres de los integrantes del grupo:

nombramiento del archivo: P1_numero_grupo -> P1_1

## <center>Ejercicio práctico semana 1</center>

<b>Maestría</b>: Inteligencia Artificial Aplicada <br>
<b>Asignatura:</b> Procesamiento Acelerado de Lenguaje Natural <br>
<b>Profesor:</b> Edwin J. Rueda

**Bienvenidos** al ejercicio práctico de la primera semana. A parte de las preguntas prácticas y teóricas que deberás responder, ten en cuenta lo siguiente:
- Encontrarás enlaces a documentación externa que te ayudará a resolver dudas.
- Resuelve los ejercicios de forma secuencial. Para que puedas ver el avance.
- La idea es guiarte sobre el proceso, por lo cual, encontrarás funciones pre-definidas.
    Por lo cual deberás colocar el código faltante dentro de las etiquetas especificadas.
- Encontrarás una salida esperada en cada celda para que tengas una guía. (Ten en cuenta que una vez ejecutada la celda, esta salida desaparecera).

### Dataset

Para este ejercicio práctico utilizaremos una fracción del dataset de MeLi. El dataset cuenta con 60k registros, los cuales hacen referencia al titulo de un producto y a su respectiva categoria. El objetivo del entregable es realizar un procesamiento del conjunto de datos con los métodos vistos en clase. Finalmente, veremos como se reduce la dimensionalidad y que tokens se vuelven más relevantes.

El dataset cuenta con la siguiente información:

    - title: Descripción del titúlo del producto
    - category: Categoria a la cual pertenece el producto

#### Descargar y visualizar el conjunto de datos

El conjunto de datos se encuentra público y puedes descargarlo [aquí](https://drive.google.com/file/d/1ivgFoL4HXwmc0u9n-rPR5c5U5lt5_Eds/view?usp=sharing). En este ejemplo, estará sobre la misma ruta donde se encuentra el notebook, por lo cual lo leemos con la función *read_csv* de [Pandas](https://pandas.pydata.org/docs/).

In [1]:
import pandas as pd
from time import time
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

/home/edwin/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
data = pd.read_csv("./filter_data.csv", index_col=0)
data.head()

,title,category
0,Campera Ls2 Hombre Discovery Black Solo En Mg ...,MOTORCYCLE_JACKETS
1,Peine Beiyuan 13 Dientes,COMBS
2,Collar Arranque Fiat Palio Siena Strada Pin Fi...,IGNITION_SWITCH_ACTUATORS
3,Lampara Compatible Benq Ms517f Por Pedido,PROJECTOR_LAMPS
4,Canilla Doble Esférico Riego Prog Lavarropa Fv...,IRRIGATION_VALVES

Primeramente, podemos obtener estadisticas de los datos:

In [3]:
print(f"Dimensionalidad de los datos: {data.shape}")
print(f"Cantidad de categorias de productos: {len(data.category.unique())}")

Dimensionalidad de los datos: (60000, 2)
Cantidad de categorias de productos: 1543

In [4]:
data.describe()

                                                    title         category
count                                               60000            60000
unique                                              59824             1543
top     Bateria Panasonic Cga-s006 S006 Dmc-fz18 Leica...  FOOTBALL_SHIRTS
freq                                                    2              137

Algo muy útil es entender la distribución de los datos, en este caso en particular, de las categorías. Esto no permitirá entender los resultados obtenidos en nuestro modelo de aprendizaje supervisado. Para ello, podemos hacer uso del método *groupby* y *count*:

In [5]:
categories = data.groupby("category").count()
categories.head()

                        title
category
3D_GLASSES                 10
3D_PRINTERS                20
3D_PRINTER_FILAMENTS       28
ABDOMINAL_TONING_BELTS      5
ABS_SENSORS                42

Otra buena práctica es observar la distribución de los datos. En este caso resulta útil ver la distribución de las categorías. Lo que nos permite enteder un poco mas a detalle los resultados que tengan nuestros modelos de AI.

In [6]:
categories.sort_values(by="title")

                           title
category
MODELISM_SERVO_MOTORS          1
MARTIAL_ARTS_CHEST_GUARDS      1
MEAT_HOOKS                     1
MOTORCYCLE_EXHAUSTS            1
BDSM_WHIPS                     1
...                          ...
REFRIGERATORS                121
SPARK_PLUGS                  124
MINI_COMPONENT_SYSTEMS       126
BABY_CAR_SEATS               129
FOOTBALL_SHIRTS              137

[1543 rows x 1 columns]

Podemos obtener la cantidad de palabras únicas en nuestro conjunto de datos antes de ser preprocesado:

In [7]:
data_init_word_count = len(np.unique(' '.join(data['title']).split()))
print(f"Tamaño inicial de palabras únicas del dataset: {data_init_word_count} palabras")

Tamaño inicial de palabras únicas del dataset: 75794 palabras

### Pregunta 1

##### ¿Crees que para los pasos de pre-procesamiento de los datos influya el tener categorías con un solo producto y otras con mas de 100 productos?

<# Puedes editar esta misma celda y escribir tu respuesta #> respuesta

### Pre-procesamiento del corpus

Para el preprocesamiento del corpus, desarrollaremos dos *pipelines*:
- Stemmer_pipeline: Este, como su nombre lo indica, se basará en sacar la raíz de las palabras. No obstante, hará los siguentes pasos:
  1. Llevará todas las palabras a minúsculas
  2. Eliminará las *stopwords*
  3. hará stemming de todo el corpus.
 
- Lemma_pipeline: Este, a diferencia del *Stemmer_pipeline*, realizará lematización de las palabras:
  1. Llevará todas las palabras a minúsculas
  2. Eliminará las *stopwords*
  3. Obtendrá el *lemma* de cada palabra.

#### Ejercicio 1
Se debe construir una función que dado un string, retorne dicho string en minúsculas:

In [8]:
def get_lower_case(sentence):
    ### TU CÓDIGO AQUÍ ###

    ######################
    return result

example = data.iloc[19]["title"]
lower_example = get_lower_case(example)
print(f"Sentencia original -> {example}")
print(f"Sentencia procesada -> {lower_example}")

Sentencia original -> Zapatilla Importada Azul Niño Talle 29 En Temperley!!!
Sentencia procesada -> zapatilla importada azul niño talle 29 en temperley!!!

#### Ejercicio 2

Ahora podemos calcular la reducción de la dimensionalidad después de llevar el corpus a minúsculas. ¿Cuantas palabras se redujimos?

In [9]:
### TU CODIGO AQUÍ ###

######################

Tamaño de palabras únicas después de aplicar lower case: 75627 palabras
Reducción de la dimensionalidad: 167 Palabras

#### Ejercicio 3
Ahora vamos a construir la función para eliminar las stopwords. Para ello, es necesario que cumpla lo siguiente:
- Recibir como entrada un string en minúsculas
- Iterar sobre cada palabra dentro del string para poder descartar las *stopwords*
- Retornar la nueva oración sin *stopwords*

In [10]:
from nltk.corpus import stopwords

def delete_stop_words(sentence):
    ### TÚ CÓDIGO AQUÍ ###
    stop_words = stopwords.words("spanish")
    
    ######################
    return result

In [11]:
print(f"Sentencia original -> {lower_example}")
example_sw = delete_stop_words(lower_example)
print(f"Sentencia sin stopwords -> {example_sw}")

Sentencia original -> zapatilla importada azul niño talle 29 en temperley!!!
Sentencia sin stopwords -> zapatilla importada azul niño talle 29 temperley!!!

#### Ejercicio 4

Ahora podemos calcular la reducción de la dimensionalidad después de eliminar del **corpus con lowercasing** las stop words. ¿Cuantas palabras se redujimos?

In [12]:
### TU CODIGO AQUÍ ###

######################

Tamaño de palabras únicas después de eliminar stop words: 75519 palabras
Reducción de la dimensionalidad: 275 Palabras

### Pregunta 2

##### ¿Crees que las mayúsculas o las *stopwords* pueden aportar a esta tarea y que eliminarlas sea un error?

<# Puedes editar esta misma celda y escribir tu respuesta #>

#### Ejercicio 5

Crear una función que nos permita lematizar las palabras/tokens dentro de unas sentencia y nos retorne la nueva sentencia lematizada:

In [13]:
import spacy
nlp_pipe = spacy.load("es_core_news_sm")

In [14]:
def get_lemmas(sentence):
    ### TÚ CÓDIGO AQUÍ ###
    result = ""

    ######################
    return result

print(f"Sentencia original -> {example_sw}")
example_lemma = get_lemmas(example_sw)
print(f"Sentencia lemmatizada -> {example_lemma}")

Sentencia original -> zapatilla importada azul niño talle 29 temperley!!!
Sentencia lemmatizada -> zapatillo importado azul niño talle 29 temperley

#### Ejercicio 6
Crear una función para sacar la raíz de cada palabra dentro de una oración y retornar la sentencia nueva procesada:

In [15]:
from nltk.stem.snowball import SnowballStemmer

def get_stemmer(sentence):
    ### TU CÓDIGO AQUÍ ###
    stemmer = SnowballStemmer('spanish')
    result = ""

    ######################
    return result

print(f"Sentencia original -> {example_sw}")
example_stemmer = get_stemmer(example_sw)
print(f"Sentencia stemming -> {example_stemmer}")

Sentencia original -> zapatilla importada azul niño talle 29 temperley!!!
Sentencia stemming -> zapatill import azul niñ tall 29 temperley!!!

#### Ejercicio 7

Ahora podemos calcular la reducción de la dimensionalidad después de hacer stemming sobre el corpus con **lowercasing y sin stop words** ¿Cuantas palabras se redujimos?

In [16]:
### TU CODIGO AQUÍ ###

######################

Tamaño de palabras únicas después de eliminar stop words: 66163 palabras
Reducción de la dimensionalidad: 9631 Palabras

#### Ejercicio 8

Con las funciones de procesamiento definidas, construiremos nuestra función *pipeline*, la cual procesará los datos dependiendo de un parámetro de entrada que define si queremos sacar el *lemma* o el *stemmer* de los tokens.

Nuestra función *pipeline* debe cumplir con los siguientes requisitos:
- recibir como entrada los siguientes parámetros:
    - df: dataframe con las columnas *title* y *category*
    - method: string identificando si es *stemmer* o *lemma* el procesado
- debe retornar el nuevo dataframe procesado, manteniendo el nombre de las columnas

In [17]:
def pipeline(df, method="stemmer"):
    """
    df: dataframe 
    method: stemmer o lemma
    """
    df = df.copy()
    for index, row in df.iterrows():
        ### TU CÓDIGO AQUÍ ###
        # no olvides utilizar las funciones ya creadas (get_lower_case, delete_stop_words, ...)
        
        ######################
    return df

Procesamos el dataset con el método *stemmer*:

In [18]:
tic = time()
data_stemmer = pipeline(data, method="stemmer")
toc = time()
print(f"Tiempo de procesamiento: {(toc-tic)/60} [min]")
data_stemmer.head()

Tiempo de procesamiento: 0.4831272562344869 [min]

,title,category
0,camper ls2 hombr discovery black sol mg bik,MOTORCYCLE_JACKETS
1,pein beiyu 13 dient,COMBS
2,coll arranqu fiat pali sien strad pin fin 140mm,IGNITION_SWITCH_ACTUATORS
3,lamp compat benq ms517f ped,PROJECTOR_LAMPS
4,canill dobl esfer rieg prog lavarrop fv 436.04...,IRRIGATION_VALVES

Procesamos el dataset con el método *lemma*

In [ ]:
tic = time()
data_lemma = pipeline(data, method="lemma")
toc = time()
print(f"Tiempo de procesamiento: {(toc-tic)/60} [min]")
data_lemma.head()

### Analicemos los resultados del procesado

Una de las formas sencillas de obtener una vista inicial de la frecuencia de los *tokens* en el corpus es mediante un [word cloud](https://github.com/amueller/word_cloud/blob/main/README.md). Con este, podemos visualmente observar que tanto cambio la frecuencia al aplicar el *stemming* o la *lemmatization*

In [ ]:
!pip install wordcloud

Para poder crear el *word cloud* necesitamos generar un único corpus:

In [17]:
corpus_init = " ".join(row["title"] for indx, row in data.iterrows())
corpus_lemma = " ".join(row["title"] for indx, row in data_lemma.iterrows())
corpus_stemmer = " ".join(row["title"] for indx, row in data_stemmer.iterrows())

In [18]:
from wordcloud import WordCloud

wc_init = WordCloud(background_color="white").generate(corpus_init)
wc_lemma = WordCloud(background_color="white").generate(corpus_lemma)
wc_stemmer = WordCloud(background_color="white").generate(corpus_stemmer)

In [ ]:
plt.figure(figsize=(20,15))
for i, wc_obj, title in zip(range(3),
                     [wc_init, wc_lemma, wc_stemmer],
                     ["Original", "Pipeline lemma", "Pipeline stemmer"]):
    plt.subplot(3,1,i+1)
    plt.title(title, fontsize=21)
    plt.imshow(wc_obj)
    plt.axis("off")

### Pregunta 3

##### Genera una conclusión de lo que logras observar en los word cloud. ¿Hubo variación en la frencuencia de los *tokens*? 
<# Puedes editar esta misma celda y escribir tu respuesta #>

#### Ejercicio 9

Nota que generamos 3 corpus (*corpus_init*, *corpus_lemma*, *corpus_stemmer*). A partir de estos tres corpus, concluye como cambió la dimensionalidad de cada corpus y el por qué cambió.

In [ ]:
### TU CÓDIGO ASÍ ###

#####################

### Pregunta 4

##### ¿Cómo podrías emplear lo visto en tu ámbito profesional? ¿Consideras útil implementar solo esta parte, o crees que se debería complementar con otras técnicas de NLP?
<# Puedes editar esta misma celda y escribir tu respuesta #>