## <center>Ejercicio práctico semana 2</center>

<b>Maestría</b>: Inteligencia Artificial Aplicada <br>
<b>Asignatura:</b> Procesamiento Acelerado de Lenguaje Natural <br>
<b>Profesor:</b> Edwin J. Rueda

**Bienvenidos** al ejercicio práctico de la segunda semana. A parte de las preguntas prácticas y teóricas que deberás responder, ten en cuenta lo siguiente:
- Encontrarás enlaces a documentación externa que te ayudará a resolver dudas.
- Resuelve los ejercicios de forma secuencial. Para que puedas ver el avance.
- La idea es guiarte sobre el proceso, por lo cual, encontrarás funciones pre-definidas.
    Por lo cual deberás colocar el código faltante dentro de las etiquetas especificadas.
- Encontrarás una salida esperada en cada celda para que tengas una guía. (Ten en cuenta que una vez ejecutada la celda, esta salida desaparecera).

Nomenclatura del archivo: P2_<# grupo>

### Dataset

Para este ejercicio práctico utilizaremos una fracción del dataset de MeLi. El dataset cuenta con 60k registros, los cuales hacen referencia al título de un producto y a su respectiva categoria. El objetivo del entregable es realizar un procesamiento del conjunto de datos con los métodos vistos en clase. Finalmente, veremos como se reduce la dimensionalidad y que tokens se vuelven más relevantes.

El dataset cuenta con la siguiente información:

    - title: Descripción del titúlo del producto
    - category: Categoria a la cual pertenece el producto

#### Descargar y visualizar el conjunto de datos

El conjunto de datos se encuentra público y puedes descargarlo [aquí](https://drive.google.com/file/d/1ivgFoL4HXwmc0u9n-rPR5c5U5lt5_Eds/view?usp=sharing). En este ejemplo, estará sobre la misma ruta donde se encuentra el notebook, por lo cual lo leemos con la función *read_csv* de [Pandas](https://pandas.pydata.org/docs/).

In [95]:
import pandas as pd
from time import time
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [114]:
data = pd.read_csv("./filter_data.csv", index_col=0)
print(data.shape)
data.head()

(60000, 2)

,title,category
0,Campera Ls2 Hombre Discovery Black Solo En Mg ...,MOTORCYCLE_JACKETS
1,Peine Beiyuan 13 Dientes,COMBS
2,Collar Arranque Fiat Palio Siena Strada Pin Fi...,IGNITION_SWITCH_ACTUATORS
3,Lampara Compatible Benq Ms517f Por Pedido,PROJECTOR_LAMPS
4,Canilla Doble Esférico Riego Prog Lavarropa Fv...,IRRIGATION_VALVES

##### Normalización de los datos

Para esta práctica, eliminaremos las stopwords, los signos de puntuación y llevaremos todas las palabras a minúsculas. Esto para disminuir la dimensionalidad del corpus y generar mejores representaciones vectoriales

In [97]:
import string
from nltk.corpus import stopwords

def normalization_sents(sentence):
    stop_words = stopwords.words("spanish")
    punc = string.punctuation
    make_trans = str.maketrans('','',punc)
    sentence = sentence.lower()
    sentence = sentence.translate(make_trans)
    new_sentence = [word for word in sentence.split() if word not in stop_words]
    return ' '.join(new_sentence)
    

def data_normalization(df):
    df = df.copy()
    df["title"] = df.title.apply(normalization_sents)
    return df

In [98]:
data_norm = data_normalization(data)
data_norm.head()

,title,category
0,campera ls2 hombre discovery black solo mg bikes,MOTORCYCLE_JACKETS
1,peine beiyuan 13 dientes,COMBS
2,collar arranque fiat palio siena strada pin fi...,IGNITION_SWITCH_ACTUATORS
3,lampara compatible benq ms517f pedido,PROJECTOR_LAMPS
4,canilla doble esférico riego prog lavarropa fv...,IRRIGATION_VALVES

##### Vamos a comparar las diferentes representaciones vectoriales
Para ello, vamos a medir las diferentes dimensiones generadas por los diferentes métodos de representación vectorial y al final del documento entrenaremos unos modelos para comparar su rendimiento:

#### Ejercicio 1

Extraer en la variable corpus todos los tokens únicos. ¿Cuantos tokens hay? <br>
**Nota**: Limitarse a extraer los tokens, no proceses mas el corpus

In [99]:
### TU CODIGO AQUI ###

######################

Cantidad de tokens únicos: 64901

#### Ejercicio 2

Codifiquemos con one-hot encoding nuestro corpus. Crea un codificador de la clase *OneHotEncoder*. ¿Que dimensión tiene la matriz entrenada? <br>
**Nota**: mantendremos la matriz dispersa para no desperdiciar memoria

In [100]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

### TU CÓDIGO AQUÍ ###

######################

Dimensión del One-Hot Encoder entrenado:
 (64901, 64901)

#### Ejericicio 3

Implementemos el método count vectorizer. ¿Cambia la dimensión de la matríz de salida? ¿Por qué?

**Nota**: Recuerde que el método *count vectorizer* recibe es las sentencias como entrada.

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

### TU CÓDIGO AQUÍ ###

######################

Dimensión del One-Hot Encoder entrenado:
 (60000, 64555)

#### Ejericio 4

Implementemos la representación vectorial TF-IDF. ¿Cual es el tamaño de la matriz generada? ¿Se diferencia a las dos matrices generadas por los métodos *OneHotEncoder* y *CountVectorizer*?

In [116]:
from sklearn.feature_extraction.text import TfidfVectorizer

### TU CÓDIGO AQUÍ ###

######################

Matriz TF-IDF:
(60000, 64555)

#### Ejercicio 5
Implementemos el word2Vec pre-entrenado de fasttext. Para ello cargue el modelo y genere una función para retornar la sentencia mas parecida a la sentencia definida como entrada. Esta similitud debe ser calculada mediante la similitud del coseno. ¿Acaso pertenecen a la misma categoria las dos sentencias?

**Nota**: No se debe retornar la misma sentencia como la mas semejante

In [ ]:
# descargamos el vector de pesos
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.vec.gz

In [ ]:
# se descomprime el vector
!gunzip cc.es.300.vec.gz

In [128]:
from gensim.models import KeyedVectors
modelo_ft = KeyedVectors.load_word2vec_format("cc.es.300.vec", binary=False)

In [183]:
from sklearn.metrics.pairwise import cosine_similarity

def get_most_similar(sentence, df, model):
    ### TU CÓDIGO AQUÍ ###

    ######################
    return (most_simil_idx, df.iloc[most_simil_idx].title, most_similar_val)

In [187]:
np.random.seed(32)
idx = np.random.choice(data_norm.index, 1)[0]
test_sent = data_norm.iloc[idx].title
print(f"sentence: {test_sent}")
result = get_most_similar(test_sent, data_norm, modelo_ft)

sentence: bolso alforja morral delantera bicicleta bike 2 botellas

In [188]:
print(f"sentencia a comparar: {test_sent} -> categoria: {data_norm.iloc[idx].category}")
print(f"sentencia mas parecida: {result[1]} -> categoría: {data_norm.iloc[result[0]].category}")
print(f"similitud del conseno: {result[2]}")

sentencia a comparar: bolso alforja morral delantera bicicleta bike 2 botellas -> categoria: BICYCLE_BAGS
sentencia mas parecida: pileta lona escalera bomba filtrado accesorios -> categoría: FRAME_POOLS
similitud del conseno: [[0.9966836]]

#### Ejercicio 6

Implementa una función que dada una sentencia/documento, retorne los $n$ documentos mas cercanos. Ten en cuenta que la métrica de similitud a usar es el coseno de la distancia. Se espera que la función retorne los indices de los $n$ documentos mas cercanos, los documentos y el valor de similitud de cada documento

In [ ]:
### TU CODIGO AQUÍ ###

######################

#### ¿Qué podemos concluir de los métodos de representación vectorial vistos?

#### Ejercicio 7

Define un método de clasificación basado en los *embeddings* para detectar la clase a la que pertence un titulo de producto.

Nota: se podria utilizar una técnica sencilla como basarse en la etiqueta de los $k$ vecinos mas cercanos

In [ ]:
### TU CODIGO AQUÍ ###

######################

### Pregunta 8

##### ¿Cómo podrías emplear lo visto en tu ámbito profesional? ¿Consideras útil implementar solo esta parte, o crees que se debería complementar con otras técnicas de NLP?
<# Puedes editar esta misma celda y escribir tu respuesta #>